import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import './globals.css';
import Header from '../components/Header';

const worksans = Work_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next.js Slider App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={worksans.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}